workflow:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-[0-9A-Za-z.-]+)?(\+[0-9A-Za-z.-]+)?$/'
      when: always
    - when: never

stages:
  - verify
  - test
  - docs

pre-release-verification:
  image: mcr.microsoft.com/dotnet/sdk:10.0
  stage: verify
  script:
    - python3 ./meta-agent/scripts/pre-release-verify.py --tag "$CI_COMMIT_TAG" --summary-out ./.meta-agent-temp/pre-release-verification/latest-summary.json
  artifacts:
    when: always
    paths:
      - .meta-agent-temp/pre-release-verification/latest-summary.json
    expire_in: 1 week

dotnet-test:
  image: mcr.microsoft.com/dotnet/sdk:10.0
  stage: test
  script:
    - python3 ./meta-agent/scripts/test-with-coverage.py
  artifacts:
    paths:
      - meta-agent/dotnet/coverage/report
      - meta-agent/dotnet/coverage/history/coverage_history.csv
    expire_in: 1 week

structurizr-site:
  image: ghcr.io/avisi-cloud/structurizr-site-generatr:latest
  stage: docs
  before_script:
    - command -v python3 >/dev/null 2>&1 || (echo "python3 is required for meta-agent verification scripts." >&2 && exit 1)
  script:
    - python3 ./meta-agent/scripts/verify-architecture.py
  artifacts:
    paths:
      - meta-agent/docs/architecture/site/build/site
    expire_in: 1 week

pages:
  image: ghcr.io/avisi-cloud/structurizr-site-generatr:latest
  stage: docs
  before_script:
    - command -v python3 >/dev/null 2>&1 || (echo "python3 is required for meta-agent verification scripts." >&2 && exit 1)
  script:
    - python3 ./meta-agent/scripts/verify-architecture.py
    - rm -rf public
    - mkdir -p public
    - cp -R meta-agent/docs/architecture/site/build/site/. public/
  artifacts:
    paths:
      - public
    expire_in: 1 week
